language: python
cache:
  pip: true
python:
  - 3.6
install:
  - pip install boto3  # Available in lambda environment
  - pip install mock
  - pip install flake8
before_script:
  - flake8 .
script: pytest
# after_success:
#   - coveralls
